# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 660)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(100000, 100000))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.centralWidget.setObjectName("centralWidget")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(120, 170, 561, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 560, 781, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.upload = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.upload.setObjectName("upload")
        self.horizontalLayout.addWidget(self.upload)
        self.download = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.download.setObjectName("download")
        self.horizontalLayout.addWidget(self.download)
        self.refresh = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.refresh.setObjectName("refresh")
        self.horizontalLayout.addWidget(self.refresh)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Quit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Quit.setObjectName("Quit")
        self.horizontalLayout.addWidget(self.Quit)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 781, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 130, 431, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Login = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Login.setObjectName("Login")
        self.horizontalLayout_2.addWidget(self.Login)
        self.Logout = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Logout.setObjectName("Logout")
        self.horizontalLayout_2.addWidget(self.Logout)
        self.Reconnect = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Reconnect.setObjectName("Reconnect")
        self.horizontalLayout_2.addWidget(self.Reconnect)
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 431, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.passWord = QtWidgets.QLabel(self.gridLayoutWidget)
        self.passWord.setObjectName("passWord")
        self.gridLayout.addWidget(self.passWord, 1, 2, 1, 1)
        self.Host = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Host.setObjectName("Host")
        self.gridLayout.addWidget(self.Host, 0, 1, 1, 1)
        self.Username = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Username.setObjectName("Username")
        self.gridLayout.addWidget(self.Username, 1, 1, 1, 1)
        self.Password = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Password.setObjectName("Password")
        self.gridLayout.addWidget(self.Password, 1, 3, 1, 1)
        self.userName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.userName.setObjectName("userName")
        self.gridLayout.addWidget(self.userName, 1, 0, 1, 1)
        self.port = QtWidgets.QLabel(self.gridLayoutWidget)
        self.port.setObjectName("port")
        self.gridLayout.addWidget(self.port, 0, 2, 1, 1)
        self.Port = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Port.setObjectName("Port")
        self.gridLayout.addWidget(self.Port, 0, 3, 1, 1)
        self.host = QtWidgets.QLabel(self.gridLayoutWidget)
        self.host.setObjectName("host")
        self.gridLayout.addWidget(self.host, 0, 0, 1, 1)
        self.sysScrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.sysScrollArea.setGeometry(QtCore.QRect(450, 30, 321, 131))
        self.sysScrollArea.setStyleSheet("")
        self.sysScrollArea.setWidgetResizable(True)
        self.sysScrollArea.setObjectName("sysScrollArea")
        self.statusPanel = QtWidgets.QWidget()
        self.statusPanel.setGeometry(QtCore.QRect(0, 0, 319, 129))
        self.statusPanel.setObjectName("statusPanel")
        self.infoList = QtWidgets.QListWidget(self.statusPanel)
        self.infoList.setGeometry(QtCore.QRect(0, 0, 321, 131))
        self.infoList.setAutoScroll(True)
        self.infoList.setObjectName("infoList")
        self.sysScrollArea.setWidget(self.statusPanel)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 170, 781, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.fileScrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.fileScrollArea.setGeometry(QtCore.QRect(10, 30, 761, 341))
        self.fileScrollArea.setWidgetResizable(True)
        self.fileScrollArea.setObjectName("fileScrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 759, 339))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.fileList = QtWidgets.QListWidget(self.scrollAreaWidgetContents_3)
        self.fileList.setGeometry(QtCore.QRect(0, 0, 761, 341))
        self.fileList.setObjectName("fileList")
        self.fileScrollArea.setWidget(self.scrollAreaWidgetContents_3)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menufile = QtWidgets.QMenu(self.menuBar)
        self.menufile.setObjectName("menufile")
        self.menutest = QtWidgets.QMenu(self.menuBar)
        self.menutest.setObjectName("menutest")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionexit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Downloads/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionexit.setIcon(icon)
        self.actionexit.setObjectName("actionexit")
        self.actionaaaa = QtWidgets.QAction(MainWindow)
        self.actionaaaa.setObjectName("actionaaaa")
        self.actionabout = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Downloads/fluidicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionabout.setIcon(icon1)
        self.actionabout.setObjectName("actionabout")
        self.menufile.addAction(self.actionexit)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionabout)
        self.menutest.addSeparator()
        self.menutest.addAction(self.actionaaaa)
        self.menuBar.addAction(self.menufile.menuAction())
        self.menuBar.addAction(self.menutest.menuAction())
        self.mainToolBar.addAction(self.actionabout)
        self.mainToolBar.addAction(self.actionexit)

        self.retranslateUi(MainWindow)
        self.Login.clicked.connect(MainWindow.login)
        self.Logout.clicked.connect(MainWindow.logout)
        self.Reconnect.clicked.connect(MainWindow.reconnect)
        self.Quit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cowry System"))
        self.upload.setText(_translate("MainWindow", "上传"))
        self.download.setText(_translate("MainWindow", "下载"))
        self.refresh.setText(_translate("MainWindow", "刷新"))
        self.Quit.setText(_translate("MainWindow", "退出"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.Login.setText(_translate("MainWindow", "登录"))
        self.Logout.setText(_translate("MainWindow", "退出"))
        self.Reconnect.setText(_translate("MainWindow", "重连"))
        self.passWord.setText(_translate("MainWindow", "密码:"))
        self.userName.setText(_translate("MainWindow", "用户名:"))
        self.port.setText(_translate("MainWindow", "端口:"))
        self.host.setText(_translate("MainWindow", "主机地址:"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menutest.setTitle(_translate("MainWindow", "test"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        self.actionexit.setShortcut(_translate("MainWindow", "Meta+Q"))
        self.actionaaaa.setText(_translate("MainWindow", "aaaa"))
        self.actionabout.setText(_translate("MainWindow", "about"))

import resources_rc
