# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uploadfiledialog.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UploadFileDialog(object):
    def setupUi(self, UploadFileDialog):
        UploadFileDialog.setObjectName("UploadFileDialog")
        UploadFileDialog.resize(427, 195)
        self.groupBox = QtWidgets.QGroupBox(UploadFileDialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 381, 141))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 361, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Note_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Note_label.setFont(font)
        self.Note_label.setObjectName("Note_label")
        self.horizontalLayout.addWidget(self.Note_label)
        self.Progress = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.Progress.setSizeIncrement(QtCore.QSize(0, 0))
        self.Progress.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.Progress.setFont(font)
        self.Progress.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Progress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Progress.setAutoFillBackground(False)
        self.Progress.setProperty("value", 24)
        self.Progress.setOrientation(QtCore.Qt.Horizontal)
        self.Progress.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.Progress.setObjectName("Progress")
        self.horizontalLayout.addWidget(self.Progress)
        spacerItem = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Percentage_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.Percentage_label.setFont(font)
        self.Percentage_label.setObjectName("Percentage_label")
        self.horizontalLayout.addWidget(self.Percentage_label)
        self.Filename = QtWidgets.QLabel(self.groupBox)
        self.Filename.setEnabled(True)
        self.Filename.setGeometry(QtCore.QRect(80, 10, 271, 57))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Filename.setFont(font)
        self.Filename.setAlignment(QtCore.Qt.AlignCenter)
        self.Filename.setWordWrap(False)
        self.Filename.setOpenExternalLinks(False)
        self.Filename.setObjectName("Filename")
        self.Filename_label = QtWidgets.QLabel(self.groupBox)
        self.Filename_label.setGeometry(QtCore.QRect(20, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Filename_label.setFont(font)
        self.Filename_label.setObjectName("Filename_label")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(UploadFileDialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 150, 381, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)

        self.retranslateUi(UploadFileDialog)
        self.pushButton_2.clicked['bool'].connect(UploadFileDialog.close)
        self.pushButton.clicked['bool'].connect(UploadFileDialog.comfirm)
        QtCore.QMetaObject.connectSlotsByName(UploadFileDialog)

    def retranslateUi(self, UploadFileDialog):
        _translate = QtCore.QCoreApplication.translate
        UploadFileDialog.setWindowTitle(_translate("UploadFileDialog", "上传进度"))
        self.groupBox.setTitle(_translate("UploadFileDialog", "Upload Status"))
        self.Note_label.setText(_translate("UploadFileDialog", "上传进度:"))
        self.Percentage_label.setText(_translate("UploadFileDialog", "100%"))
        self.Filename.setText(_translate("UploadFileDialog", "examplexxxxx.zip"))
        self.Filename_label.setText(_translate("UploadFileDialog", "文件名:"))
        self.pushButton_2.setText(_translate("UploadFileDialog", "取消"))
        self.pushButton.setText(_translate("UploadFileDialog", "确认"))

