        self.fileTree.topLevelItem(0).setText(0, _translate("MainWindow", "/"))
        self.fileTree.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "sw"))
        self.fileTree.topLevelItem(0).child(1).setText(1, _translate("MainWindow", "a"))
        self.fileTree.topLevelItem(0).child(1).setText(2, _translate("MainWindow", "a"))
        self.fileTree.topLevelItem(0).child(1).setText(3, _translate("MainWindow", "a"))
